// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $about from "./routes/about.tsx";
import * as $books from "./routes/books.tsx";
import * as $index from "./routes/index.tsx";
import * as $posts_slug_ from "./routes/posts/[slug].tsx";
import * as $posts_random from "./routes/posts/random.tsx";
import * as $search from "./routes/search.tsx";

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/about.tsx": $about,
    "./routes/books.tsx": $books,
    "./routes/index.tsx": $index,
    "./routes/posts/[slug].tsx": $posts_slug_,
    "./routes/posts/random.tsx": $posts_random,
    "./routes/search.tsx": $search,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
